apiVersion: apps/v1
kind: Deployment
metadata:
    name: teamb-kubernetes
    labels: &labels
        apps: teamb-kubernetes

spec:
    
    selector:
        matchLabels: *labels
    replicas: 1
    revisionHistoryLimit: 10
    template:
        metadata:
            labels: *labels
        spec:
            containers:
            - name: teamb-kubernetes
              image: mfumo/teamb-docker-kubernetes:V1
              command: ["./binary"]